development:
  adapter: postgresql
  encoding: utf8
  database: restaurant_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: restaurant_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: restaurant_production
  pool: 5
  host: localhost
